FROM dtcpronto/ros-jazzy:l4t 

RUN sudo apt update && sudo apt install -y \
 python3-zmq \
 default-jre \
 iputils-ping \
 python3-lz4 \
 python3-defusedxml \
 ros-jazzy-smach

WORKDIR /root
RUN mv /ws .

RUN cd ws/src && git clone https://github.com/dtc-pronto/dtc-msgs

COPY interface_rajant ws/src/interface_rajant
COPY mocha_core ws/src/mocha_core
COPY mocha_launch ws/src/mocha_launch

RUN /opt/venv/bin/pip3 install --extra-index-url https://pypi.org/simple catkin_pkg
RUN python3 -m venv /opt/venv --system-site-packages

RUN /bin/bash -c "\
    source /opt/ros/jazzy/setup.bash && \
    cd /root/ws && \
    colcon build --symlink-install --cmake-clean-cache"

COPY ./entrypoint.bash entrypoint.bash
RUN sudo chmod +x entrypoint.bash

