basestation:
  node-type: "base_station"
  IP-address: "10.10.10.100"
  using-radio: "brick-1"
  base-port: "1234"
  clients:
    - "callisto"
    - "europa"
    - "io"
    - "titan"

europa:
  node-type: "ground_robot"
  IP-address: "10.10.10.101"
  using-radio: "blue-2"
  base-port: "2234"
  clients:
    - "basestation"
    - "callisto"
    - "io"
    - "titan"

callisto:
  node-type: "ground_robot"
  IP-address: "10.10.10.102"
  using-radio: "blue-6"
  base-port: "3234"
  clients:
    - "basestation"
    - "europa"
    - "io"
    - "titan"

io:
  node-type: "ground_robot"
  IP-address: "10.10.10.103"
  using-radio: "blue-5"
  base-port: "4234"
  clients:
    - "basestation"
    - "europa"
    - "callisto"
    - "titan"

titan:
  node-type: "aerial_robot"
  IP-address: "10.10.10.107"
  using-radio: "blue-1"
  base-port: "6234"
  clients:
    - "basestation"
    - "callisto"
    - "europa"
    - "io"
