basestation:
  node-type: "base_station"
  IP-address: "10.10.10.100"
  using-radio: "brick-1"
  base-port: "1234"
  clients:
    - "callisto"
    - "europa"
    - "titan"

europa:
  node-type: "ground_robot"
  IP-address: "10.10.10.101"
  using-radio: "black-1"
  base-port: "2234"
  clients:
    - "groundstation"
    - "callisto"
    - "titan"

callisto:
  node-type: "ground_robot"
  IP-address: "10.10.10.102"
  using-radio: "black-1"
  base-port: "3234"
  clients:
    - "groundstation"
    - "europa"
    - "titan"

titan:
  node-type: "aerial_robot"
  IP-address: "10.10.10.107"
  using-radio: "black-1"
  base-port: "6234"
  clients:
    - "groundstation"
    - "callisto"
    - "europa"
