brick-1:
        SN: "ME4-2450R-58845"
        MAC-address: ["04:f0:21:38:cf:5b", "04:f0:21:38:86:bd"]
        computed-IP-address: "10.229.221.1"

brick-2:
        SN: "ME4-2450R-58846"
        MAC-address: ["04:f0:21:38:d3:be", "04:f0:21:38:86:c9"]
        computed-IP-address: "10.229.222.1"

blue-1:
        SN: "OMAHA-50-63915"
        MAC-address: ["cc:2d:e0:9b:3e:aa"]
        computed-IP-address: "10.249.171.1"

blue-2:
        SN: "OMAHA-50-63935"
        MAC-address: ["cc:2d:e0:9b:3e:46"]
        computed-IP-address: "10.249.191.1"

blue-3:
        SN: "OMAHA-50-67211"
        MAC-address: ["b8:69:f4:70:ba:90"]
        computed-IP-address: "10.6.139.1"

blue-4:
        SN: "OMAHA-50-67212"
        MAC-address: ["b8:69:f4:70:ba:bc"]
        computed-IP-address: "10.6.140.1"

blue-5:
        SN: "OMAHA-50-67213"
        MAC-address: ["b8:69:f4:70:ba:0f"]
        computed-IP-address: "10.6.141.1"

blue-6:
        SN: "DX2-50-67783"
        MAC-address: ["74:4d:28:41:7a:e6"]
        computed-IP-address: "10.8.199.1"

black-1:
        SN: "ME4-2450R-41075"
        MAC-address: ["04:f0:21:2f:6d:ab", "04:f0:21:17:e4:51"]
        computed-IP-address: "10.160.115.1"

black-2:
        SN: "ME4-2450R-46136"
        MAC-address: ["04:f0:21:13:13:e7", "04:f0:21:02:e1:39"]
        computed-IP-address: "10.180.56.1"

black-3:
        SN: "ME4-2450R-58161"
        MAC-address: ["04:f0:21:1c:1b:21", "04:f0:21:19:b1:bb"]
        computed-IP-address: "10.227.49.1"

black-4:
        SN: "ME4-2450R-46130"
        MAC-address: ["04:f0:21:13:13:e4", "04:f0:21:02:e1:4a"]
        computed-IP-address: "10.180.50.1"

cardinal-1:
        SN: "AG1-5250M-117082"
        MAC-address: ["84:8d:84:ef:13:7e","84:8d:84:ef:13:7f"]
        computed-IP-address: "10.201.90.1"

cardinal-2:
        SN: "AG1-5250M-117113"
        MAC-address: ["84:8d:84:ef:13:8d","84:8d:84:ef:13:8e"]
        computed-IP-address: "10.201.121.1"

cardinal-3:
        SN: "AG1-5250M-117098"
        MAC-address: ["84:8d:84:ef:0d:7b","84:8d:84:ef:0d:7c"]
        computed-IP-address: "10.201.106.1"

deep-blue-1:
        SN: "DX2-50-81745"
        MAC-address: ["c4:ad:34:79:e4:da"]
        computed-IP-address: "10.63.81.1"

deep-blue-2:
        SN: "DX2-50-100071"
        MAC-address: ["dc:2c:6e:bc:e2:8e"]
        computed-IP-address: "10.134.231.1"

deep-blue-3:
        SN: "DX2-24-119294"
        MAC-address: ["48:a9:8a:a0:75:69"]
        computed-IP-address: 10.209.254.1

deep-blue-4:
        SN: "DX2-24-125991"
        MAC-address: ["48:8f:5a:48:8f:38"]
        computed-IP-address: 10.236.39.1

deep-blue-5:
        SN: "DX2-24-125992"
        MAC-address: ["2c:c8:1b:e1:9b:d6"]
        computed-IP-address: 10.236.40.1

dx4-1:
        SN: "DX4-5252E-106727"
        MAC-address: ["00:0e:8e:bd:d9:24", "00:0e:8e:bd:d9:23"]
        computed-IP-address: "10.160.231.1"

dx4-2:
        SN: "DX4-5252E-106742"
        MAC-address: ["00:0e:8e:bd:d9:31", "00:0e:8e:bd:29:2a"]
        computed-IP-address: "10.160.246.1"

dx4-3:
        SN: "DX4-5252E-106741"
        MAC-address: ["00:0e:8e:bd:d8:e9", "00:0e:8e:bd:d0:03"]
        computed-IP-address: "10.160.245.1"

dx4-4:
        SN: "DX4-5252E-106737"
        MAC-address: ["00:0e:8e:bd:d9:35", "00:0e:8e:bd:d9:30"]
        computed-IP-address: "10.160.241.1"

dx4-5:
        SN: "DX4-5252E-106739"
        MAC-address: ["00:0e:8e:bd:d9:37", "00:0e:8e:bd:d9:29"]
        computed-IP-address: "10.160.243.1"

dx4-6:
        SN: "DX4-5252E-106740"
        MAC-address: ["00:0e:8e:bd:d6:e5", "00:0e:8e:bd:d9:32"]
        computed-IP-address: "10.160.244.1"

dx4-7:
        SN: "DX4-5252E-106744"
        MAC-address: ["00:0e:8e:a0:ae:5e", "00:0e:8e:a0:ae:57"]
        computed-IP-address: "10.160.248.1"

super-brick:
        SN: "PE1-2255B-103860"
        MAC-address: ["84:8d:84:41:4f:fb", "84:8d:84:41:4f:f7", "84:8d:84:41:4f:f8", "84:8d:84:41:4f:f9"]
        computed-IP-address: "10.149.180.1"

