basestation:
  node-type: "base_station"
  IP-address: "10.10.10.100"
  using-radio: "super-brick"
  base-port: "1234"
  clients:
    - "io"
    - "callisto"
    - "apollo"
    - "triton"
#    - "europa"
#    - "titan"

triton:
  node-type: "ground_robot"
  IP-address: "10.10.10.104"
  using-radio: "dx4-4"
  base-port: "2234"
  clients:
    - "basestation"
    - "callisto"
    - "io"
    - "apollo"


# europa:
#   node-type: "ground_robot"
#   IP-address: "10.10.10.101"
#   using-radio: "blue-2"
#   base-port: "2234"
#   clients:
#     - "basestation"
#     - "callisto"
#     - "io"
#     - "titan"
# 

apollo:
  node-type: "ground_robot"
  IP-address: "10.10.10.142"
  using-radio: "cardinal-2"
  base-port: "6234"
  clients:
    - "basestation"
    - "callisto"
    - "io"
    - "triton"


callisto:
  node-type: "ground_robot"
  IP-address: "10.10.10.102"
  using-radio: "blue-6"
  base-port: "3234"
  clients:
    - "basestation"
    - "io"
    - "apollo"
    - "triton"
 #   - "europa"
 #   - "titan"

io:
  node-type: "ground_robot"
  IP-address: "10.10.10.103"
  using-radio: "blue-5"
  base-port: "4234"
  clients:
    - "basestation"
    - "callisto"
    - "apollo"
    - "triton"
#    - "europa"
#    - "titan"

# titan:
#   node-type: "aerial_robot"
#   IP-address: "10.10.10.107"
#   using-radio: "blue-1"
#   base-port: "6234"
#   clients:
#     - "basestation"
#     - "callisto"
#     - "europa"
#     - "io"

