ground_robot:
  - msg_topic: "/dgps/antenna1/fix"
    msg_type: "sensor_msgs/NavSatFix"
    msg_priority: "HIGH_PRIORITY"
    msg_history: "LAST_MESSAGE"

  - msg_topic: "/triage_report/gate1"
    msg_type: "dtc_msgs/Gate1"
    msg_priority: "HIGH_PRIORITY"
    msg_history: "LAST_MESSAGE"
  
  - msg_topic: "/triage_report/gate2"
    msg_type: "dtc_msgs/Gate2"
    msg_priority: "HIGH_PRIORITY"
    msg_history: "LAST_MESSAGE"
  
  - msg_topic: "/triage_report/gate3"
    msg_type: "dtc_msgs/Gate3"
    msg_priority: "HIGH_PRIORITY"
    msg_history: "LAST_MESSAGE"
  
  - msg_topic: "/triage_report/gate4"
    msg_type: "dtc_msgs/Gate4"
    msg_priority: "HIGH_PRIORITY"
    msg_history: "LAST_MESSAGE"

aerial_robot:
  - msg_topic: "/dgps/antenna1/fix"
    msg_type: "sensor_msgs/NavSatFix"
    msg_priority: "HIGH_PRIORITY"
    msg_history: "LAST_MESSAGE"

  - msg_topic: "/glider/casualty/fix"
    msg_type: "dtc_msgs/CasualtyFixArray"
    msg_priority: "HIGH_PRIORITY"
    msg_history: "LAST_MESSAGE" 

base_station:
  - msg_topic: "/dummy"
    msg_type: "std_msgs/Header"
    msg_priority: "HIGH_PRIORITY"
    msg_history: "LAST_MESSAGE"
