groundstation:
        is-active: True
        IP-address: "127.0.0.1"
        using-radio: "brick-1"
        base-port: "1234"
        clients:
          "charon": 1
          "styx": 2
          "quad1": 3
          "quad2": 4

charon:
        is-active: True
        IP-address: "127.0.0.1"
        using-radio: "black-1"
        base-port: "2234"
        clients:
          "groundstation": 1
          "styx": 2
          "quad1": 3
          "quad2": 4

styx:
        is-active: True
        IP-address: "127.0.0.1"
        using-radio: "black-2"
        base-port: "3234"
        clients:
          "groundstation": 1
          "charon": 2
          "quad1": 3
          "quad2": 4


quad1:
        is-active: False
        IP-address: "127.0.0.1"
        using-radio: "blue-1"
        base-port: "4234"
        clients:
          "groundstation": 1
          "charon": 2
          "quad1": 3
          "quad2": 4

quad2:
        is-active: False
        IP-address: "127.0.0.1"
        using-radio: "blue-2"
        base-port: "5234"
        clients:
          "groundstation": 1
          "charon": 2
          "styx": 3
          "quad1": 4
