# ROS 2 build pipeline
name: build

on:
  push:
    branches: [ros2]
  pull_request:
    branches: [ros2]
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0'

jobs:
  build:
    strategy:
      matrix:
        ros_distro: [humble, jazzy]

    runs-on: ubuntu-latest
    container: osrf/ros:${{ matrix.ros_distro }}-desktop
    steps:
      - uses: actions/checkout@v4

      - name: Apt dependencies
        run: |
          apt-get update
          apt-get install -qy python3-colcon-common-extensions python3-rosdep
          apt-get install -qy python3-colorama python3-zmq python3-lz4 python3-pytest ros-${ROS_DISTRO}-smach
          rosdep update
          rosdep install --from-paths . --ignore-src -y -r --as-root apt:false

      - name: Build workspace
        run: |
          . /opt/ros/${{ matrix.ros_distro }}/setup.sh
          colcon build --event-handlers console_direct+

      - name: Run Tests
        run: |
          . /opt/ros/${{ matrix.ros_distro }}/setup.sh
          colcon test --event-handlers console_direct+
          colcon test-result --verbose
